### ISSUE TITLE
Avatar fail to load and render username twice

### ISSUE THREAD

**Issue by inquiringtimes** [busyorg/busy#806]
<img src="http://imgur.com/EiKwphdl.png" />

#### Actual behavior

Some strange doubling of text.

#### How to reproduce

* Browser: Chrome newest version.
* Operating system: Linux mint newest version.

I suppose I could try the other browsers to see what they do... but i'm tired so.. thanks for the upvote.  I'll make sure and report any weird stuff I see.

**Comment by inquiringtimes** [comment]
ok.. well that's fixed

**Comment by espoem** [comment]
Not fixed yet.

<img src="https://user-images.githubusercontent.com/16621517/31738083-cc46f844-b449-11e7-8a0c-350fa7bafabd.png" height="280px"/>

**Comment by bonustrack** [comment]
This is issue is related to this repo: https://github.com/busyorg/busy-img It's happening when steemd node is not available or a request fail.

**Comment by Sekhmet** [comment]
This has been kind-of-fixed in #905
Now, when busy-img is down it will use default image for avatars.

**Comment by jm90m** [comment]
Closing this, as @Sekhmet had pointed it out it was fixed in (https://github.com/busyorg/busy/pull/905)

**Comment by jm90m** [comment]
The root issue is not solved, which is - busy-img goes down temporarily, but we can create a new issue for that.
